version: '3.9'
services:
  mysql:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
  zookeeper:
    image: 'zookeeper'
  kafka:
    depends_on: [ 'zookeeper' ]
    image: 'confluentinc/cp-kafka'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  kafka-init:
    depends_on: [ 'kafka' ]
    image: 'confluentinc/cp-kafka'
    entrypoint:
      - /bin/bash
      - '-c'
    command: |-
      "
      kafka-topics --bootstrap-server kafka:9092 --list
      function create {
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --replication-factor 1 --partitions 3 --topic $1
      }

      create topic

      echo 'kafka topics created'
      "
